name: bron_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.12.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  gap: ^3.0.1
  glass_liquid_navbar: ^0.2.0
  package_info_plus: ^8.0.2
  shared_preferences: ^2.5.5
  cupertino_native: ^0.1.1
  yandex_mapkit: ^4.3.0
  geolocator: ^13.0.2
  mobile_scanner: ^7.1.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  uuid: ^4.5.1
  shimmer: ^3.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/nav_icons/
    - assets/icons/main_icons/
